build:
  info:
    type: "{cipher}AYCEVGnVQOtwwDdjo7amL/S0fbWdHedx8VUo49++gsaEel2pDaIudiEXLBLfjqZkvP923zaMAGz7zgRjESazvhfrfDgCObXO6PAiKP1VJi+1ZYvoSG4d1wczdpO9Wxjk0lVotxkqWMauWb2mZ9WchxN9G3BdDl0tawJRASOOjZR+54JulmnAITeuYrR+dXZlAqivmYQS/ycMdtED13KkPefvdCHvR9StS8VXUpqXkU86T5ukDXOFtIZ3kDJ49vtL+2qHCBUXMRV3ghVn8aoYqRDiiN+8IWyFaMtZmgehkBlu5cRGibAzuFhJcWoxcMpx1625YCE53NKc3ElllYKflqRkqOMNn2ZPoB1BtQbf15WNN8No1gw/a/t9P5J9xbuV1AtsaAUE6F7jjvfIGMq5RzEPniiCuqXuTiZbptpyZ3cA+GnuqLgORs3Od/SMBYtmsgO5E6bJ1YibWe6vMpUQwS6/gBm65gYqFjwaAEYPFJGoR8CeVgxqu6qaVQpx+5mRevV2gui8AEKF3sv998YOJWJvsWZh9xgzBTbE5DwZSUAQLMJgXomBoGA38+G6CNbUyWQ="

    id: 103
